coverage:
  status:
    project:
      default:
        target: 82%
    patch: off

github_checks:
    annotations: true

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: backend
      carryforward: true
      statuses:
        - type: project
          target: 85%
    - name: migrations
      carryforward: true
      statuses:
        - type: project
          target: 40%
    - name: pui
      carryforward: true
      statuses:
        - type: project
          target: 45%
